_wandb:
    value:
        cli_version: 0.22.3
        e:
            wclkmyws74mkb7bbiwlda9erasqv2g7w:
                args:
                    - --pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0
                    - --pretrained_vae_model_name_or_path=madebyollin/sdxl-vae-fp16-fix
                    - --instance_data_dir=./data/monet_style
                    - --output_dir=./outputs/lora_baseline_monet
                    - --instance_prompt=a painting in the style of monet
                    - --resolution=1024
                    - --train_batch_size=8
                    - --gradient_accumulation_steps=1
                    - --learning_rate=1e-4
                    - --max_train_steps=1000
                    - --lora_rank=32
                codePath: src/train_lora_reg.py
                codePathLocal: src/train_lora_reg.py
                cpu_count: 128
                cpu_count_logical: 256
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "409930686464"
                        used: "62488379392"
                email: shivamsinghal@tamu.edu
                executable: /home/shivamsinghal/miniconda3/envs/gen/bin/python3.10
                gpu: NVIDIA H100 NVL
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-041c541b-6dcf-f2a6-1259-8d701d973384
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-a98f3fdb-ad45-b66d-3ff7-27a99f03432e
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-fb51941f-b1a9-44da-13a7-9c701dbf59b5
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-86e46df3-6fca-376e-2cc1-3fbc0d906ed9
                host: csce-galanti-s1.engr.tamu.edu
                memory:
                    total: "1217102848000"
                os: Linux-6.14.0-33-generic-x86_64-with-glibc2.39
                program: /home/shivamsinghal/LTC/GEN/./src/train_lora_reg.py
                python: CPython 3.10.19
                root: /home/shivamsinghal/LTC/GEN
                startedAt: "2025-11-05T23:22:06.134124Z"
                writerId: wclkmyws74mkb7bbiwlda9erasqv2g7w
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 83
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 83
                - 98
            "3":
                - 2
                - 61
            "4": 3.10.19
            "5": 0.22.3
            "6": 4.57.1
            "12": 0.22.3
            "13": linux-x86_64
gradient_accumulation_steps:
    value: 1
instance_data_dir:
    value: ./data/monet_style
instance_prompt:
    value: a painting in the style of monet
lambda_reg:
    value: 1
learning_rate:
    value: 0.0001
lora_rank:
    value: 32
lr_scheduler:
    value: constant
lr_warmup_steps:
    value: 0
max_train_steps:
    value: 1000
mixed_precision:
    value: fp16
output_dir:
    value: ./outputs/lora_baseline_monet
pretrained_model_name_or_path:
    value: stabilityai/stable-diffusion-xl-base-1.0
pretrained_vae_model_name_or_path:
    value: madebyollin/sdxl-vae-fp16-fix
prior_prompt_list:
    value: a cat,a dog,a car,a landscape
resolution:
    value: 1024
seed:
    value: 42
train_batch_size:
    value: 8
use_regularization:
    value: false
